uploadDirectory: /Users/currycarr/   # expects trailing slash
hashFilename: false                  # expects true or false
url: skenav.io
server:
  applicationConnectors:
    - type: http
      port: 80
assets:
  overrides:
    /files: /Users/currycarr/usercontent/